name: 'student_perform'
version: '1.0.0'
config-version: 2

profile: 'student_perform'

model-paths: 
  - "models/marts"
  - "models/staging"
  - "models/intermediate"
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  student_perform:
    marts:
      +materialized: table
      +tags: ["marts"]
      +description: "Tabelas finais do meu Modelo de Dados."
    intermediate:
      +materialized: ephemeral
      +tags: ["intermediate"]
      +description: "Tabelas intermediárias do meu Modelo de Dados."
    staging:
      +materialized: table
      +tags: ["staging"]
      +description: "Tabelas de staging do meu Modelo de Dados."
      +tests:
        - not_null:
            column_name: "id"
        - unique:
            column_name: "id"

seeds:
  student_perform:
    student-mat:
      table_name: student_mat
      schema: raw

    student-por:
      table_name: student_por
      schema: raw